export const homeObjOne = {
    lightBg : false,
    topLine : 'Welcome!',
    LightText : true,
    LightTextDesc : true,
    description : 'Quick Quiz Knowledge Booster For A Perfect Level Up ',
    buttonLable : 'Log In',
    img : './svg-1.svg',
    alt : 'Credit card',
    imgStart : '',
    headline : 'Qui',
    headline2:'zz',
    headline3:'ee Qui',
    headline4:'z',
}